@echo off
echo.
echo Creating master 00index file...
echo.
echo ------------------ > 00index
type BASS\00INDEX >> 00index
echo ------------------ >> 00index
type BLIPS\00INDEX >> 00index
echo ------------------ >> 00index
type CHORD\00INDEX >> 00index
echo ------------------ >> 00index
type DRONES\00INDEX >> 00index
echo ------------------ >> 00index
type GUITAR\00INDEX >> 00index
echo ------------------ >> 00index
type LEAD\00INDEX >> 00index
echo ------------------ >> 00index
type PERC\BASE\00INDEX >> 00index
echo ------------------ >> 00index
type PERC\DRUMS\00INDEX >> 00index
echo ------------------ >> 00index
type PERC\LEAD\00INDEX >> 00index
echo ------------------ >> 00index

